### ISSUE TITLE
APMode funktioniert nicht

### ISSUE THREAD

**Issue by rola25** [polygontwist/ESP_sonoff_Schaltuhr#1]
Hallo,

Der APMode scheint nicht zu funktionieren. Das WLAN ist zwar kurz sichtbar, aber die Verbindung funktioniert nicht. Liegt das ev. daran, dass alle 10 Sekunden vom AP-Mode in den Client-Modus geschaltet wird und so eine Verbinudng nicht zustande kommen kann?

-rp-

**Comment by rola25** [comment]
Bin selbst draufgekommen: keinAPModus muss auf false gesetzt werden, dann funktioniert die Verbindung nach 100 Sekunden

**Comment by polygontwist** [comment]
ja das ist richtig. Ich habe das Problem das sich meine Dosen ab und zu aus dem WLAN ausklinken und die 10 Versuche (#define anzahlVersuche * #define check_wlanasclient=100 Sekunden) für eine Neuverbindung nicht gereicht haben, deshalb das "keinAPModus ". Wenn der AP Modus früher an sein soll, musst Du die Parameter runter setzen (anzahlVersuche auf 1 => nur 10sec warten).
